# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
# NOTE: This stage was built with the bindist Use flag enabled

COMMON_FLAGS="-march=skylake -mabm --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=8192 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

#PORTAGE OPTIONS

PORTAGE_NICENESS=1
MAKEOPTS="-j9 -l16"
FEATURES="candy parallel-install parallel-fetch preserve-libs buildpkg getbinpkg"
VIDEO_CARDS="intel nvidia"
INPUT_DEVICES="libinput joystick synaptics"
EMERGE_DEFAULT_OPTS=""

#GENTOO MIRRORS

GENTOO_MIRRORS="https://ftp.fau.de/gentoo http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ https://ftp.agdsn.de/gentoo http://mirror.netcologne.de/gentoo/ http://ftp.halifax.rwth-aachen.de/gentoo/ http://ftp.uni-stuttgart.de/gentoo-distfiles/ http://mirror.netzwerge.de/gentoo/ https://mirror.dogado.de/gentoo https://mirror.leaseweb.com/gentoo/ https://mirrors.evoluso.com/gentoo/"

#USE FLAGS

USE="-gnome -kde -systemd -wayland -cdr -dvd -floppy -cdda -cups -qemu \
     -networkmanager -dvdr -geoip -snapd -flatpak -ipod -geoloc -virtualbox\
     -css -dvb -emacs -geolocation -clamav -gimp -gps -ibm -ios \
     -plasma -rss -selinux -semantic-desktop -telemetry -xemacs \
     -mysql -mplayer -cdinstall -atm -oci8 -oci8-instant-client \
     -xfce -Xaw3d -coreaudio -debug -test -scanner -vcd -webkit \ 
     hardened X pipewire savedconfig dist-kernel dbus policykit polkit"

#ACCEPTS

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

#GRUB BOOTLOADER
GRUB_PLATFORMS="efi-64"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.

LC_MESSAGES=C.utf8
