#!/bin/bash

case $1/$2 in
  pre/*)
    # Put here any commands expected to be run when suspending or hibernating.
    ip link set enp0s31f6 down
    ip link set wlp2s0 down
    modprobe -r e1000e
    modprobe -r iwlwifi
    sleep 1
    systemctl stop NetworkManager
    ;;
  post/*)
    # Put here any commands expected to be run when resuming from suspension or thawing from hibernation.
    modprobe -v e1000e
    modprobe -v iwlwifi
    ip link set enp0s31f6 up
    ip link set wlp2s0 up
    sleep 1
    systemctl start NetworkManager
    ;;
esac
