#!/bin/bash

case $1/$2 in
  pre/*)
    # Put here any commands expected to be run when suspending or hibernating.
    modprobe -r e1000e
    sleep 1
    modprobe -r iwlwifi
    ;;
  post/*)
    # Put here any commands expected to be run when resuming from suspension or thawing from hibernation.
    modprobe -v e1000e
    modprobe -v iwlwifi
    ;;
esac
